### ISSUE TITLE
Indexed read fails for filelists if length of inidices for individual file is 0

### ISSUE THREAD

**Issue by erin717** [legend-exp/legend-pydataobj#125]
When performing an indexed read on a list of files using a global list of indices, we break the global index list into a local list for each file. However, if the local index list for a file is empty, then the read fails. I haven't done an extensive investigation, but this seems to be an issue specific to reading in `VectorOfVectors`.

```
import glob
from lgdo import lh5

filelist = sorted(glob.glob('/global/cfs/cdirs/m2676/data/lngs/l200/public/prodenv/prod-blind/ref-raw/generated/tier/raw/cal/p11/r001/*.lh5'))

idxs = [1666, 2339, 3203, 3302, 5343]

sto = lh5.LH5Store()
n_rows = sto.read("ch1105603/raw/daqenergy", filelist)[1]
n_rows_first_file = sto.read("ch1105603/raw/daqenergy", filelist[0])[1]

print(f"Length of all entries in filelist is {n_rows}")
print(f"Length of entries in first file is {n_rows_first_file}")

data = sto.read("ch1105603/raw", filelist, idx = idxs)[0]
```
This gives the following output below as well as an error message stored in [errormessage.txt](https://github.com/user-attachments/files/18212300/errormessage.txt):
```
Length of all entries in filelist is 221723
Length of entries in first file is 330
```

**Comment by iguinn** [comment]
Thanks for reporting and testing this
