### ISSUE TITLE
Implement histogram LH5 specification

### ISSUE THREAD

**Issue by gipert** [legend-exp/legend-pydataobj#15]
Serialization/deserialization of [hist.Hist](hist.readthedocs.io) objects to LH5.

Specification: https://legend-exp.github.io/legend-data-format-specs/dev/hdf5/#Histograms

**Comment by MoritzNeuberger** [comment]
So I experimented a bit with a possible implementation. @gipert had the idea to implement a `LGDO` wrapper for `hist.Hist` (or more precisely `hist.BaseHist` [[link](https://github.com/scikit-hep/hist/blob/main/src/hist/basehist.py)]) using multiple inheritance. One problem I ran into while playing around is that I get a TypeError mentioning that the metaclasses of `LGDO` and `Hist` are not compatible. I'm not an expert in this area, so I don't really know how to fix this. Do you have any idea how to work around this?

**Comment by MoritzNeuberger** [comment]
The implementation so far looks like this btw:
```
class Histogram(LGDO,Hist):
    def __init__(self, 
                *in_args: hist.AxisTypes | hist.Storage | str,
                storage: hist.Storage | str | None = None,
                metadata: Any = None,
                data: np.typing.NDArray[Any] | None = None,
                label: str | None = None,
                name: str | None = None,
                attrs: dict[str, Any] = None,) -> None:

        LGDO.__init__(self,attrs)
        hist.Hist.__init__(self,in_args,storage,metadata,data,label,name)
```

**Comment by gipert** [comment]
Indeed:
```pycon
>>> class Histogram(LGDO, BaseHist):
>>>     def __init__(
>>>         self,
>>>         attrs=None,
>>>         **kwargs,
>>>     ):
>>>         super(LGDO).__init__(attrs)
>>>         super(BaseHist).__init__(**kwargs)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```
But I'm not an expert, I guess some more research is needed. Also `hist` ppl seem to use quite advanced python subclassing stuff in `basehist.py`, we could maybe ask them.

**Comment by gipert** [comment]
https://hist.readthedocs.io/en/latest/user-guide/subclassing.html!

**Comment by ManuelHu** [comment]
So the problem is really that `LGDO` has `ABC` as a metaclass, and  Hist has something different. Even
```python
from hist import Hist
from lgdo import LGDO

class Histogram(LGDO, Hist):
    pass
```
is already crashing.
---

But 
```python
from abc import ABCMeta
from hist import Hist
from lgdo import LGDO

class HistogramMeta(ABCMeta, Hist.__class__):
    pass

class Histogram(LGDO, Hist, metaclass=HistogramMeta):
    pass
```
is working :-)
