### ISSUE TITLE
Loading just the first entry in a file causes read to crash

### ISSUE THREAD

**Issue by ggmarshall** [legend-exp/legend-pydataobj#55]
Minimal version here:
```
tb_data,_ = sto.read_object(
    f"{channel}/raw",
    input_file[5],
    idx=np.array([0]),
    n_rows=1,
)
```
This also affects when loading in across multiple files and 1 file happens to just have one entry in idx which is the first entry in a file. Related to lines 630-636 where idx2 is defined:
```
              idx2 = (np.asarray(idx[0]).copy() - 1,)
              # re-read cumulative_length with these indices
              # note this will allocate memory for fd_starts!
              fd_start = None
              if idx2[0][0] == -1:
                  idx2 = (idx2[0][1:],)
                  fd_start = 0  # this variable avoids an ndarray append
```
If idx only contains 1 entry which is 0 then idx2 becomes an empty array

**Comment by gipert** [comment]
Is this something we broke or has never been working?

**Comment by ggmarshall** [comment]
not sure I only just found it as it crashed the production

**Comment by gipert** [comment]
Can you add a test + fix?
